import { Car } from "@/models/Car";

export async function getCarSeeds(): Promise<Car[]> {
    return [
        {
            manufacturer: 'Audi',
            model: 'TT',
            manufacture_year: 2006,
            registration_date: 2009,
            license_plate: '1AU1234',
            vin: 'WAUZZZ8JX6A000001',
            fuel_category: 1,
            car_nickname: 'TéTéčko',
            tank_capacity: 55,
            odometer: 140000,
        },
        {
            manufacturer: 'Volkswagen',
            model: 'Golf',
            manufacture_year: 2012,
            registration_date: 2013,
            license_plate: '2VW5678',
            vin: 'WVWZZZ1KZDW000002',
            fuel_category: 2,
            car_nickname: 'Golfík',
            tank_capacity: 50,
            odometer: 142300,
        },
        {
            manufacturer: 'Toyota',
            model: 'Corolla',
            manufacture_year: 2019,
            registration_date: 2020,
            license_plate: '3TO9876',
            vin: 'JTDBR32E520000003',
            fuel_category: 1,
            car_nickname: 'Korela',
            tank_capacity: 55,
            odometer: 65300,
        },
        {
            manufacturer: 'Dacia',
            model: 'Duster',
            manufacture_year: 2018,
            registration_date: 2019,
            license_plate: '4DC3456',
            vin: 'UU1HSDHN000000004',
            fuel_category: 1,
            car_nickname: 'Dusterka',
            tank_capacity: 50,
            odometer: 104500,
        },
        {
            manufacturer: 'Peugeot',
            model: '208',
            manufacture_year: 2020,
            registration_date: 2021,
            license_plate: '5PG7890',
            vin: 'VF3CUHMR000000005',
            fuel_category: 1,
            car_nickname: 'Pěťule',
            tank_capacity: 44,
            odometer: 34500,
        },
        {
            manufacturer: 'Ford',
            model: 'Focus',
            manufacture_year: 2016,
            registration_date: 2016,
            license_plate: '6FO4567',
            vin: 'WF0AXXWPDA0000006',
            fuel_category: 1,
            car_nickname: 'Modrák',
            tank_capacity: 55,
            odometer: 98500,
        },
        {
            manufacturer: 'Hyundai',
            model: 'i30',
            manufacture_year: 2017,
            registration_date: 2018,
            license_plate: '7HY7891',
            vin: 'KMHD741DBHU000007',
            fuel_category: 1,
            car_nickname: 'Hájíčko',
            tank_capacity: 53,
            odometer: 76800,
        },
        {
            manufacturer: 'Renault',
            model: 'Clio',
            manufacture_year: 2013,
            registration_date: 2014,
            license_plate: '8RN6543',
            vin: 'VF15R040000000008',
            fuel_category: 1,
            car_nickname: 'Klijo',
            tank_capacity: 45,
            odometer: 119200,
        },
        {
            manufacturer: 'Opel',
            model: 'Astra',
            manufacture_year: 2014,
            registration_date: 2015,
            license_plate: '9OP1239',
            vin: 'W0L0ZCF6840000009',
            fuel_category: 1,
            car_nickname: 'Astrička',
            tank_capacity: 52,
            odometer: 133000,
        },
        {
            manufacturer: 'Tesla',
            model: 'Model 3',
            manufacture_year: 2021,
            registration_date: 2022,
            license_plate: '1TS5678',
            vin: '5YJ3E1EA5MF000010',
            fuel_category: 1,
            car_nickname: 'Teslička',
            tank_capacity: 0,
            odometer: 25300,
        },
    ];
}