import { Part } from "@/models/Part";


export function createPartSeed(overrides: Partial<Part> = {}): Part {
    return {
        name: 'Olejový filtr',
        manufacturer: 'MANN-FILTER',
        oem_code: 'HU 716/2 X',
        description: 'Olejový filtr pro vozy VW, Audi, Seat, Škoda',
        price: 130,
        count: 5,
        unit: 'ks',
        created_at: Date.now(),
        updated_at: Date.now(),
        ...overrides,
    };
}

export async function getPartSeeds() {
    return [
        createPartSeed({
            name: 'Olejový filtr',
            manufacturer: 'MANN-FILTER',
            oem_code: 'HU 716/2 X',
            description: 'Olejový filtr pro vozy VW, Audi, Seat, Škoda',
            price: 130,
            count: 5,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
        createPartSeed({
            name: 'Vzduchový filtr',
            manufacturer: 'Bosch',
            oem_code: '1 457 433 557',
            description: 'Vzduchový filtr pro benzinové motory 1.6',
            price: 220,
            count: 3,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Brzdové destičky přední',
            manufacturer: 'Brembo',
            oem_code: 'P 85 020',
            description: 'Sada předních brzdových destiček pro Škoda Octavia II',
            price: 950,
            count: 2,
            unit: 'sada',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Motorový olej 5W-30',
            manufacturer: 'Castrol',
            oem_code: '15669E',
            description: 'Syntetický olej pro benzinové i naftové motory',
            price: 450,
            count: 4,
            unit: 'l',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Žárovka H7',
            manufacturer: 'Philips',
            oem_code: '12972PRC1',
            description: 'Halogenová žárovka do předního světlometu',
            price: 80,
            count: 10,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Stěrač přední 600mm',
            manufacturer: 'Valeo',
            oem_code: '574153',
            description: 'Univerzální plochý stěrač 600 mm',
            price: 190,
            count: 6,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Palivový filtr',
            manufacturer: 'Mahle',
            oem_code: 'KL 228/1',
            description: 'Palivový filtr pro naftové motory TDI',
            price: 280,
            count: 3,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Zapalovací svíčka',
            manufacturer: 'NGK',
            oem_code: 'BKR6EQUP',
            description: 'Svíčka pro benzinové motory 1.6 a 1.8',
            price: 110,
            count: 8,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
          createPartSeed({
            name: 'Kabínový filtr s aktivním uhlím',
            manufacturer: 'Purflux',
            oem_code: 'AHC219',
            description: 'Filtr pro čistý vzduch v kabině, pohlcuje pachy',
            price: 260,
            count: 4,
            unit: 'ks',
            created_at: Date.now(),
            updated_at: Date.now(),
          }),
    ];
}